export const pagesData = [
    {
        id:"8",
        title: "Galleria slideshow site",
        desc: "Art Gallery Slideshow with masonry layout, slideshow logic with auto/manual play and lightbox view", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/mctvqcomxdsv3cgawo4f.jpg",
        category:"intermediate",
        type: "multi", 
        link:"https://galleria-demo.netlify.app/",
    },
    {
        id:"7",
        title: "Photosnap multi-page website",
        desc: "Four pages App with beautiful image galleries and diverse page layouts. Fully responsive for all devices.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/bgjwz6i6nfnqngx7ae36.jpg",
        category:"advanced",
        type: "multi", 
        link:"https://photosnap-demo.netlify.app/",
    },
    {
        id:"1",
        title: "Arch Studio multi-page website",
        desc: "App with inner pages such as Home, Portfolio, About and Contact pages. Fully mobile and tablet friendly.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/aywluxa3cncqcu26m3vi.jpg",
        category:"advanced",
        type: "multi", 
        link:"https://archstudios.netlify.app/",
    },
    {
        id:"4",
        title: "Planets fact site",
        desc: "Each planet from our solar system has a dedicated page with three subsections. Smooth Mobile Nav Menu.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/wrljilk72cxhipdjyhpa.jpg",
        category:"junior",
        type: "multi", 
        link:"/pages/planet-facts",
    },
    {
        id:"6",
        title: "Coffeeroasters subscription site",
        desc: "Multi pages with lots of different layouts optimized for mobile and tablet. Interactive subscription form as an accordion. ", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/qwfjjtc2edfogm32keno.jpg",
        category:"intermediate",
        type: "multi", 
        link:"/pages/coffee-roasters",
    },
    {
        id:"2",
        title: "Easybank landing page",
        desc: "Landing page with multiple sections done with CSS Flexbox and Grid. Optimized for mobile devices", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/o4iyywkwjc31epcmsmyo.jpg",
        category:"intermediate",
        type: "multi", 
        link:"https://easybank-landingp.netlify.app/",
    },
    {
        id:"5",
        title: "Dine restaurant website",
        desc: "2-page commercial App consisting of Homepage with multiple sections including subsections, separate Booking page with Form", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/glyb3m1iuyv9y8zzmmxc.jpg",
        category:"intermediate",
        type: "multi", 
        link:"/pages/dine-restaurant",
    },
    {
        id:"3",
        title: "Sunnyside agency landing page",
        desc: "Modern and colorful landing page with multiple sections and different image layouts using CSS Grid and Flexbox. Mobile and Tablet friendly", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/wqzotbyfysz9pbfk9jus.jpg",
        category:"junior",
        type: "multi", 
        link:"/pages/sunnyside",
    },
]