export const componentCardData = [
    {
        id:"9",
        title: "News homepage",
        desc: "Multi-sectioned News Landing page, optimized responsive view for tablet and mobile devices as well.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/abbzt6kmkawmpbj7evxx.jpg",
        category:"junior",
        type: "component", 
        link:"/components/news-homepage",
    },
    {
        id:"10",
        title: "Github User Search",
        desc: "Fully responsive, interactive component allowing users to search real GitHub Users and displays user data using Fetch API. Includes Light & Dark modes.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/Challenges/nr37our6z7faztmhwj9r.jpg?__cpo=aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20.jpg",
        category:"junior",
        type: "component", 
        link:"/components/github-user",
    },
    {
        id:"1",
        title: "NFT preview card component",
        desc: "Personalized Card Component with Flexbox CSS and Hover Effects.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/rinokvkluq95madbvtmk.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/nft-card",
    },
    {
        id:"3",
        title: "Product preview card",
        desc: "Responsive Product component, built with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/lftjtn81b7brs2icc898.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/perfume-card",
    },
    {
        id:"4",
        title: "FAQ accordion card",
        desc: "Responsive FAQ Accordion, showing/hiding answers", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/ua4zwoxu3i9avrzrusre.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/faq",
    },
    {
        id:"5",
        title: "Four card feature section",
        desc: "Multi-column and responsive layouts with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/a3b5gbgtfbtiqrdawpwp.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/four-cards",
    },
    {
        id:"6",
        title: "QR code component",
        desc: "Minimal yet clean QR card with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/qh97gysgjrzqyqlig2al.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/qr",
    },
    {
        id:"7",
        title: "Order summary component",
        desc: "Playful order card feature preview built with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/ouobx6tvyduidzio7wr7.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/order-summary",
    },
    {
        id:"8",
        title: "Article preview component",
        desc: "Article Card with micro-interaction animations built with CSS", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/tm7zwaa7fprabjbwbemt.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/article-preview",
    },
    {
        id:"2",
        title: "Advice Generator App",
        desc: "Fetching JSON Data from from the Advice Slip API to generate random quotes of advice", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/sfl8uqvq75wnnr559ksp.jpg",
        category:"junior",
        type: "component", 
        link:"/components/advice-gen",
    }, 
]