export const componentCardData = [
    {
        id:"15",
        title: "Multi-step form",
        desc: "Modern, fully responsive multi-step form with form validation and state management using React JS", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/lpwvfibpdyycvjpukkec.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/multi-step-form",
    },
    {
        id:"18",
        title: "E-commerce product page",
        desc: "Lightbox Desktop Image Gallery & Slider Images Gallery for mobile, Functions to add items to cart. Smooth mobile Nav", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/fhzpdnabrek50hvhftnl.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/product-page",
    },
    {
        id:"9",
        title: "News homepage",
        desc: "Multi-sectioned News Landing page, optimized responsive view for tablet and mobile devices as well.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/abbzt6kmkawmpbj7evxx.jpg",
        category:"junior",
        type: "component", 
        link:"/components/news-homepage",
    },
    {
        id:"14",
        title: "Room homepage",
        desc: "Responsive homepage built with CSS Grid, including Image gallery with slider function and mobile toggle navbar menu", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/m1v21ubdjc2n75bl8p7n.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/room-homepage",
    },
    {
        id:"10",
        title: "Github User Search",
        desc: "Fully responsive, interactive component allowing users to search real GitHub Users and displays user data using Fetch API. Includes Light & Dark modes.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/Challenges/nr37our6z7faztmhwj9r.jpg?__cpo=aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20.jpg",
        category:"junior",
        type: "component", 
        link:"/components/github-user",
    },
    {
        id:"11",
        title: "Expenses chart component",
        desc: "Data visualization with dynamic JSON data using Javascript", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/Challenges/qqz8vfg0jzmrtk2liteo.jpg",
        category:"junior",
        type: "component", 
        link:"/components/expense-chart",
    },
    {
        id:"1",
        title: "NFT preview card component",
        desc: "Personalized Card Component with Flexbox CSS and Hover Effects.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/rinokvkluq95madbvtmk.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/nft-card",
    },
    {
        id:"16",
        title: "Todo app",
        desc: "Fully interactive, responsive Todo app with add, delete and filter functions using React JS", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/ty4ppudcq94rtgj4rv6p.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/todo",
    },
    {
        id:"17",
        title: "Job listings with filtering",
        desc: "Filter out jobs based on selected category or multiple categories.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/vhouwacmyw27vhcvq8zm.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/static-jobs",
    },
    {
        id:"12",
        title: "Pricing component with toggle",
        desc: "Animated toggle to choose pricing plans", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/Challenges/pzkdrqu0lizrk8qgmiti.jpg",
        category:"junior",
        type: "component", 
        link:"/components/pricing-toggle",
    },
    {
        id:"19",
        title: "Results summary component",
        desc: "Animated results summary component with data fetching from external server", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/b03akozsxsouireonkkd.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/results-summary",
    },
    {
        id:"3",
        title: "Product preview card",
        desc: "Responsive Product component, built with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/lftjtn81b7brs2icc898.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/perfume-card",
    },
    {
        id:"4",
        title: "FAQ accordion card",
        desc: "Responsive FAQ Accordion, showing/hiding answers", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/ua4zwoxu3i9avrzrusre.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/faq",
    },
    {
        id:"5",
        title: "Four card feature section",
        desc: "Multi-column and responsive layouts with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/a3b5gbgtfbtiqrdawpwp.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/four-cards",
    },
    {
        id:"6",
        title: "QR code component",
        desc: "Minimal yet clean QR card with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/qh97gysgjrzqyqlig2al.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/qr",
    },
    {
        id:"7",
        title: "Order summary component",
        desc: "Playful order card feature preview built with CSS Flexbox", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/ouobx6tvyduidzio7wr7.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/order-summary",
    },
    {
        id:"8",
        title: "Article preview component",
        desc: "Article Card with micro-interaction animations built with CSS", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/tm7zwaa7fprabjbwbemt.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/article-preview",
    },
    {
        id:"2",
        title: "Advice Generator App",
        desc: "Fetching JSON Data from from the Advice Slip API to generate random quotes of advice", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/sfl8uqvq75wnnr559ksp.jpg",
        category:"junior",
        type: "component", 
        link:"/components/advice-gen",
    }, 
    {
        id:"13",
        title: "Testimonials grid section",
        desc: "Multiple complex layouts for different device sizes with CSS Grid", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/Challenges/h05k6b7pqcylnhsw8pqs.jpg",
        category:"junior",
        type: "component", 
        link:"/components/testimonials",
    }, 
    {
        id:"20",
        title: "Profile card component",
        desc: "A simple animated profile card with background decoration", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/dia0o9uigiiz4gebiqps.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/profile-card",
    }, 
    {
        id:"21",
        title: "Stats preview card component",
        desc: "Smoothly Animated Card component with color filter using pure CSS", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_475/Challenges/sucvvhutd4codsxpzvw7.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/stats-preview",
    }, 
    {
        id:"22",
        title: "Notifications page",
        desc: "Smoothly Animated Notification list, fetching data dynamically from JSON, which is hosted online. Images are hosted on Cloudinary.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/hkmsdxxteijprjdzskhg.jpg",
        category:"junior",
        type: "page", 
        link:"https://notifications-page-fm-challenge.netlify.app/",
    }, 
    {
        id:"23",
        title: "Interactive rating component",
        desc: "Animated interactive rating component with a loader animation using framer-motion.", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/dm3s8oqtz0mwcaygqjhy.jpg",
        category:"newbie",
        type: "page", 
        link:"https://mini-rating-component.netlify.app/",
    }, 
    {
        id:"24",
        title: "Interactive comments section",
        desc: "Comment Section", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/v9wskl4mnbt5gbxm4o2r.jpg",
        category:"intermediate",
        type: "component", 
        link:"/components/comment-section",
    }, 
    {
        id:"25",
        title: "Base Apparel - Coming Soon",
        desc: "Base Apparel Coming Soon Landing Page Animated in GSAP", 
        img: "https://res.cloudinary.com/dz209s6jk/image/upload/f_auto,q_auto,w_700/Challenges/oxwdbpj64r1au0gp1frc.jpg",
        category:"newbie",
        type: "component", 
        link:"/components/base-apparel",
    }, 
]